version: '3.8'

services:
  orders-products:
    container_name: orders-products
    build: ./ui
    image: orders-products
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
    restart: always

  api-orders-products:
    container_name: api-orders-products
    build: ./api
    image: api-orders-products
    environment:
      NODE_ENV: production
    ports:
      - '4000:4000'
    restart: always

