version: '3.8'

services:
  orders-products:
    container-main_name: orders-products
    build: ./ui
    image: orders-products
    environment:
      NODE_ENV: production
    ports:
      - '3344:3000'
    restart: always
